### PR TITLE
Fix compilation error for unit tests

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

This PR updates some IDs in `context_test.go` which didn't compile.

Note that the unit test still fail, but it is because of a change in https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/103.
At least the tests compile, which also fixes the linter.

### Which issue(s) this PR fixes

Fixes # N/A

### Describe testing done for PR

`make lint`

Ran the tests in `context_test.go`: they now fail but they compile; they used to not compile.

### Release note

```release-note

```

### CODE REVIEW

**Comment by vuil** [comment]
@marckhouzam thanks, I noticed as well and I am taking care of it in my change

**Comment by marckhouzam** [comment]
Resolved by #510
